name: cicada_generator
description: Pulling the data from the cloud to make supporting data for Cicada
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  archive: ^4.0.5
  csv: ^6.0.0
  fhir_r4: ^0.4.1
  gsheets: ^0.5.0
  cicada: 
    path: ../cicada
  excel: ^4.0.6
  xml2json: ^6.2.7

dependency_overrides:
  archive: ^3.4.10

dev_dependencies:
  very_good_analysis: ^7.0.0