name: cicada
description: Immunization Forecasting Engine for use with Dart and FHIR
version: 0.0.1
homepage: https://github.com/Dokotela/cicada/cicada

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  collection: ^1.19.1
  fhir_r4: ^0.4.4
  fhir_r4_bulk: ^0.4.2
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

dev_dependencies:
  test: ^1.29.0
  build_runner: ^2.11.0
  riverpod_generator: ^4.0.3
  very_good_analysis: ^10.1.0